### ISSUE TITLE
NuGet not compatible with Castle.Windsor >= 4?

### ISSUE THREAD

**Issue by janv8000** [Particular/NServiceBus.CastleWindsor#34]
The NServiceBus.CastleWindsor nuget at version 6.0.0 specifies the following dependency ranges:

* NServiceBus [6.0.0, 7.0.0)
* Castle.Windsor [3.3.0, 4.0.0)

Is it possible to release an updated nuget (eg. 6.1.0) referencing NServiceBus v6 and Castle.Windsor v4+ (eg. `[3.3.0, 5.0.0)`)?

If it's not possible, how come?

**Comment by janv8000** [comment]
New release on nuget.org missing after #25?

**Comment by WilliamBZA** [comment]
Hi @janv8000, we'll get a release out for you soon. In the meantime you can simply ignore dependencies in nuget when you install the Castle v4 package.

**Comment by boblangley** [comment]
@janv8000 6.1.0, which expands the package range, is up on NuGet now.

**Comment by janv8000** [comment]
Thanks a lot!

**Comment by IwanowM** [comment]
Hi, I have the same question about `NServiceBus.CastleWindsor` and `Castle Windsor v5.0.0` 

Is it possible now to use `NServiceBus.CastleWindsor` with `Castle Windsor v5.0.0` despite of package restrictions - `<PackageReference Include="Castle.Windsor" Version="[4.1.0, 5.0.0)" />` ?
Are there any problems to release `NServiceBus.CastleWindsor` with `Castle Windsor v5.0.0`?
