### ISSUE TITLE
Singletons registered for multiple interfaces results in multiple instances instead of one as expected

### ISSUE THREAD

**Issue by mark-robert-hill** [Particular/NServiceBus.CastleWindsor#48]
I am not sure if the issue is here or elsewhere but I can confirm that the issue does not occur without the windsor container but once added the issue occurs.

Basically, any mutator that implements more than one mutator interface will have a component registered for each interface but each of the registered components are registered for all interfaces.

to reproduce download the MessageMutators sample, 

1. run the sample
2. hit s to send a valid message
3. note the compression messages. 
4. stop the sample.
5. update NServiceBus to 6.4.3
6. install NServiceBus.Windsor
7. add the following code right after the endpointConfiguration is created
 `var container = new WindsorContainer();`
`endpointConfiguration.UseContainer<WindsorBuilder>(
 		    customizations: customizations =>
 		    {
 			    customizations.ExistingContainer(container);
 		    });
`

8. run the sample.
9. hit s to send a valid message
10. note the mutator is run twice now
11.

**Comment by WilliamBZA** [comment]
Thanks @mark-robert-hill. I'll dig into this and see what the reason is

**Comment by boblangley** [comment]
@mark-robert-hill We have released NServiceBus.CastleWindsor 6.1.1 to NuGet with a fix for this issue. Thank you for letting us know about it.

**Comment by mark-robert-hill** [comment]
thanks for the quick fix!
