### ISSUE TITLE
Support for Windsor 5

### ISSUE THREAD

**Issue by LeMaciek** [Particular/NServiceBus.CastleWindsor#58]
Please add suppprt for windsor5 - https://github.com/castleproject/Windsor/releases

**Comment by dbelcham** [comment]
Hi @LeMaciek. We're looking into this and it's likely that adding this support will come in a future maintenance release. We're not sure exactly when that will be, but this will get included in the planning of it.

**Comment by jethrob** [comment]
I created a pull request for Windsor 5.0.0 support.
Seems to be working in my application.

**Comment by LeMaciek** [comment]
@dbelcham any news?

**Comment by dbelcham** [comment]
@LeMaciek This has been working its way to the top of our to-do list. No firm date on when it will be done but it is nearing the top.

**Comment by tmasternak** [comment]
Hi, @LeMaciek we just released the newest version on [nuget](https://www.nuget.org/packages/NServiceBus.CastleWindsor/7.1.0) that supports Castle.Windsor 5.0.0.
