### ISSUE TITLE
Using an existing container could fail with TypedFactoryFacility

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/NServiceBus.CastleWindsor#8]
## Repro:

1. Add NServiceBus.Newtonsoft.Json and configure the endpoint to use it
2. Create a new instance of `WindsorContainer` and configure it to use `TypedFactoryFacility`
3. Send a message

```
var container = new WindsorContainer();
container.AddFacility<TypedFactoryFacility>();

BusConfiguration busConfiguration = new BusConfiguration();
busConfiguration.UseSerialization<NewtonsoftSerializer>();
busConfiguration.UseContainer<WindsorBuilder>(b => b.ExistingContainer(container));

busConfiguration.UsePersistence<InMemoryPersistence>();
busConfiguration.EnableInstallers();

using (IBus bus = Bus.Create(busConfiguration).Start())
{
    bus.SendLocal(new CreateOrder {});
}
```

## Behavior:
Application throws an exception that `Newtonsoft.Json.JsonWriter` is not registered in the container.

## Cause
The cause is the `TypedFactoryFacility` which uses implicit registration to replace all `Func<T>`'s with a `CastleProxy` that wraps the `Func<T>`, causing the code to try and resolve the types via the container instead of using the code provided in the `Func<T>`.

The implicit registration looks for any publicly accessible `Func<T>`'s and wraps them.

## Potential fixes:
We could ask our users to not use the `TypedFactoryFacility`

Another approach is to change from using a `Func<Stream, JsonReader>`/`Func<String, JsonWriter>` to using an interface that is equivalent to the `Func<>`s.

@Particular/container-maintainers as per the triage process I need another set of eyes on this to confirm the scheduling

**Comment by tmasternak** [comment]
Removing `Tag: Consider for Short Term Focus`. @WilliamBZA please use `Consider for Promotion` if it's still relevant.

**Comment by WilliamBZA** [comment]
@tmasternak there is no `Consider for Promotion` tag

**Comment by tmasternak** [comment]
@WilliamBZA I've created the tag and added it to this issue.

**Comment by andreasohlund** [comment]
Is this a fix to the current version or targeted for vNext?

**Comment by WilliamBZA** [comment]
Depends on when it gets a WIP slot :smile:

It's not a critical as there is a workaround. vNext is my suggestion.

**Comment by andreasohlund** [comment]
Is it a breaking change?

**Comment by WilliamBZA** [comment]
No.

**Comment by boblangley** [comment]
@Particular/container-maintainers Do we want to get this done for V6 launch as discussed above? I think we should.

**Comment by WilliamBZA** [comment]
This has already been fixed in V6. Closing this issue.

:-1: to Backporting, as there is a valid workaround as documented [here](https://groups.google.com/d/msg/particularsoftware/vYopuQ7SWnI/QDPUXfGWBQAJ).
